// Tests for the device-side automatic-logoff safeguard (HIPAA
// §164.312(a)(2)(iii)).
//
// This file previously held the default counter-app smoke test generated by
// `flutter create`. It referenced a `MyApp` class that has never existed in
// this project, so it could not compile — and `flutter_test` was missing from
// dev_dependencies, so `flutter analyze` reported errors on every run.
//
// Run with:  flutter test

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:usmlewise_christ/services/idle_lock.dart';

void main() {
  group('IdleLock', () {
    testWidgets('signs out after the configured idle period', (tester) async {
      var expired = 0;
      final lock = IdleLock(timeout: const Duration(seconds: 2))
        ..onExpired = () async => expired++;

      await tester.pumpWidget(
        IdleLockScope(lock: lock, child: const SizedBox.expand()),
      );
      lock.enable();

      await tester.pump(const Duration(seconds: 1));
      expect(expired, 0, reason: 'still inside the idle window');

      await tester.pump(const Duration(seconds: 2));
      expect(expired, 1, reason: 'idle window elapsed');

      lock.disable();
    });

    testWidgets('interaction pushes the deadline back', (tester) async {
      var expired = 0;
      final lock = IdleLock(timeout: const Duration(seconds: 2))
        ..onExpired = () async => expired++;

      await tester.pumpWidget(
        IdleLockScope(lock: lock, child: const SizedBox.expand()),
      );
      lock.enable();

      // Tap just before expiry — a collector mid-survey must not be kicked out.
      await tester.pump(const Duration(milliseconds: 1500));
      await tester.tapAt(const Offset(50, 50));
      await tester.pump(const Duration(milliseconds: 1500));
      expect(expired, 0, reason: 'the tap should have reset the timer');

      await tester.pump(const Duration(seconds: 2));
      expect(expired, 1, reason: 'idle again after the tap');

      lock.disable();
    });

    testWidgets('a disabled lock never fires', (tester) async {
      var expired = 0;
      final lock = IdleLock(timeout: const Duration(seconds: 1))
        ..onExpired = () async => expired++;

      await tester.pumpWidget(
        IdleLockScope(lock: lock, child: const SizedBox.expand()),
      );
      lock.enable();
      lock.disable();

      await tester.pump(const Duration(seconds: 3));
      expect(expired, 0, reason: 'a signed-out session has nothing to lock');
    });

    testWidgets('configure() applies a new window immediately', (tester) async {
      var expired = 0;
      final lock = IdleLock(timeout: const Duration(minutes: 30))
        ..onExpired = () async => expired++;

      await tester.pumpWidget(
        IdleLockScope(lock: lock, child: const SizedBox.expand()),
      );
      lock.enable();
      // The server can tighten the window centrally; it must take effect on
      // the running session, not only at the next sign-in.
      lock.configure(const Duration(seconds: 2));

      await tester.pump(const Duration(seconds: 3));
      expect(expired, 1);

      lock.disable();
    });
  });
}
